# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0008_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserData')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=500)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image')),
                ('imageRelation', models.ManyToManyField(related_name='tags', to='image.Image')),
            ],
        ),
    ]
