# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tagRelation',
        ),
        migrations.AddField(
            model_name='image',
            name='Tags',
            field=models.ManyToManyField(related_name='Images', to='image.Tag'),
        ),
    ]
