# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagtext',
            old_name='length',
            new_name='h',
        ),
        migrations.RenameField(
            model_name='tagtext',
            old_name='tag',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tagtext',
            old_name='width',
            new_name='w',
        ),
        migrations.RenameField(
            model_name='tagtext',
            old_name='xCoordinate',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='tagtext',
            old_name='yCoordinate',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='tagusername',
            old_name='length',
            new_name='h',
        ),
        migrations.RenameField(
            model_name='tagusername',
            old_name='tag',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tagusername',
            old_name='width',
            new_name='w',
        ),
        migrations.RenameField(
            model_name='tagusername',
            old_name='xCoordinate',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='tagusername',
            old_name='yCoordinate',
            new_name='y',
        ),
    ]
