# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
    ]
