# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20170125_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='unique_id',
        ),
    ]
