# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0003_remove_image_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
