# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20161229_1802'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0003_remove_image_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.UserData'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image.Image'),
        ),
    ]
