# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20170704_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=225, unique=True),
        ),
    ]
