# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20161229_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_text',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
