# # -*- coding: utf-8 -*-
# # Generated by Django 1.11.3 on 2017-07-07 22:40
# from __future__ import unicode_literals

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('image', '0006_auto_20170704_1418'),
#         ('image', '0004_image_uploaded_by'),
#     ]

#     operations = [
#     ]
