# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_merge_20170707_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTextRectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('xCoordinate', models.FloatField(blank=True, null=True)),
                ('yCoordinate', models.FloatField(blank=True, null=True)),
                ('tag_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.TagText')),
            ],
        ),
        migrations.AddField(
            model_name='tagusername',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagusername',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagusername',
            name='xCoordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagusername',
            name='yCoordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
