# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_userdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
