# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20161203_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
    ]
