# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_image_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
